# frozen_string_literal: true

# Load the Rails application.
require_relative "config/application"

# Initialize the Rails application (only if not already initialized)
Rails.application.load_tasks unless Rails.application.initialized?
